spring.application.name=Config-Default

# Use IP address instead of hostname while registering with Eureka
# Helpful when hostname resolution fails (common in local/dev setups)
eureka.instance.prefer-ip-address=true


# Register this service to Eureka Server. Means: "I am a microservice, add me to service registry"
eureka.client.register-with-eureka=true


# Fetch registry (list of all services) from Eureka Server. Needed for service-to-service communication
eureka.client.fetch-registry=true


# URL of Eureka Server where this service will register
# defaultZone = main Eureka server endpoint
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
